### POST create an account
POST http://localhost:3000/account

{
  "firstName": "John",
  "lastName": "Smith"
}

### GET all Accounts
GET http://localhost:3000/account

### GET one account
GET http://localhost:3000/account/1

###GET one account with invalid JWT token
GET http://localhost:3000/account/1
x-jwt-token: thisIsNotAValidToken

### DELETE one account
DELETE http://localhost:3000/account/1

###POST to transfer to one account
POST http://localhost:3000/transfer

{
  "toAccount": 456788,
  "amount": 250
}