### GET all Accounts
GET http://localhost:3000/account

### GET one account
GET http://localhost:3000/account/1234

### POST create an account
POST http://localhost:3000/account

{
  "firstName": "John",
  "lastName": "Smith"
}