### POST create an account
POST http://localhost:3000/account

{
  "firstName": "John",
  "lastName": "Smith",
  "password": "goodpassword3232"
}

###POST to login
# Number is given when the account is created 
POST http://localhost:3000/login

{
  "number": 441944,
  "password": "goodpassword3232"
}

### GET all Accounts
GET http://localhost:3000/account

### GET one account
# This will error because a valid JWT is needed
GET http://localhost:3000/account/1

### GET one account with valid JWT
# JWT below should be the one returned from POST login
GET http://localhost:3000/account/7
x-jwt-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50TnVtYmVyIjo2NTI0MDYsImV4cGlyZXNBdCI6MTUwMDB9.9jDiWo-2KUPJzy4rQamvXiRSij4AiCJm7fVmrAeffHM

### DELETE one account
DELETE http://localhost:3000/account/1

###POST to transfer to one account
POST http://localhost:3000/transfer

{
  "toAccount": 441944,
  "amount": 250
}